export const roomsData = [
  {
    _id: "1",
    name: "Conference Room 1",
    roomNo: 101,
    floorNo: 1,
    capacity: 15,
    pricePerSlot: 80,
    thumbnail: "https://t4.ftcdn.net/jpg/00/80/91/11/360_F_80911186_RoBCsyLrNTrG7Y1EOyCsaCJO5DyHgTox.jpg",
    extraImages: [
      "https://example.com/images/conference-room-1-1.jpg",
      "https://example.com/images/conference-room-1-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "2",
    name: "Conference Room 2",
    roomNo: 102,
    floorNo: 1,
    capacity: 20,
    pricePerSlot: 100,
    thumbnail: "https://media.istockphoto.com/id/1290582628/photo/meeting-room-interior-with-empty-tv-screen.jpg?s=612x612&w=0&k=20&c=3-xefV3cnHcYuVuzBKJnXvU5A1yzFeMSeiOSsJHO9o8=",
    extraImages: [
      "https://example.com/images/conference-room-2-1.jpg",
      "https://example.com/images/conference-room-2-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "3",
    name: "Conference Room 3",
    roomNo: 103,
    floorNo: 1,
    capacity: 25,
    pricePerSlot: 120,
    thumbnail: "https://t3.ftcdn.net/jpg/01/67/00/68/360_F_167006826_2X4YTrNkjmVs96QC8aX522j7MyNukXnc.jpg",
    extraImages: [
      "https://example.com/images/conference-room-3-1.jpg",
      "https://example.com/images/conference-room-3-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "4",
    name: "Conference Room 4",
    roomNo: 104,
    floorNo: 1,
    capacity: 30,
    pricePerSlot: 140,
    thumbnail: "https://images.unsplash.com/photo-1582653291997-079a1c04e5a1?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fG1lZXRpbmclMjByb29tfGVufDB8fDB8fHww",
    extraImages: [
      "https://example.com/images/conference-room-4-1.jpg",
      "https://example.com/images/conference-room-4-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "5",
    name: "Conference Room 5",
    roomNo: 105,    
    floorNo: 2,
    capacity: 18,
    pricePerSlot: 90,
    thumbnail: "https://plus.unsplash.com/premium_photo-1724753995771-8ee6954e78da?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZW1wdHklMjBtZWV0aW5nJTIwcm9vbXxlbnwwfHwwfHx8MA%3D%3D",
    extraImages: [
      "https://example.com/images/conference-room-5-1.jpg",
      "https://example.com/images/conference-room-5-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "6",
    name: "Conference Room 6",
    roomNo: 106,
    floorNo: 2,
    capacity: 22,
    pricePerSlot: 110,
    thumbnail: "https://media.istockphoto.com/id/1498273728/photo/modern-business-office-conference-room-3d-rendering.jpg?s=612x612&w=0&k=20&c=kMEXCviX1OJ32k3-hieBXYjUz1_SSohQ78vzqjeG05E=",
    extraImages: [
      "https://example.com/images/conference-room-6-1.jpg",
      "https://example.com/images/conference-room-6-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "7",
    name: "Conference Room 7",
    roomNo: 107,
    floorNo: 2,
    capacity: 24,
    pricePerSlot: 130,
    thumbnail: "https://cdn.prod.website-files.com/61cdc308bda4b01d29c5fc56/61e8c69bb963388c44a4d0b8_large-video-screen-meeting-room.jpeg",
    extraImages: [
      "https://example.com/images/conference-room-7-1.jpg",
      "https://example.com/images/conference-room-7-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "8",
    name: "Conference Room 8",
    roomNo: 108,
    floorNo: 2,
    capacity: 28,
    pricePerSlot: 150,
    thumbnail: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTF8fG1lZXRpbmclMjByb29tfGVufDB8fDB8fHww",
    extraImages: [
      "https://example.com/images/conference-room-8-1.jpg",
      "https://example.com/images/conference-room-8-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "9",
    name: "Conference Room 9",
    roomNo: 109,
    floorNo: 3,
    capacity: 16,
    pricePerSlot: 95,
    thumbnail: "https://www.centrepoint.com/Images/Silom_Meeting_Room-Silom.jpg",
    extraImages: [
      "https://example.com/images/conference-room-9-1.jpg",
      "https://example.com/images/conference-room-9-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "10",
    name: "Conference Room 10",
    roomNo: 110,
    floorNo: 3,
    capacity: 21,
    pricePerSlot: 105,
    thumbnail: "https://d3hw3resvc2uti.cloudfront.net/www.jakartapondokindah.intercontinental.com-1545092690/cms/cache/v2/5fedb81b56c9a.jpeg/1920x1080/fit/80/7d78698a0142440822eacbe21411e50f.jpg",
    extraImages: [
      "https://example.com/images/conference-room-10-1.jpg",
      "https://example.com/images/conference-room-10-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "11",
    name: "Conference Room 11",
    roomNo: 111,
    floorNo: 3,
    capacity: 19,
    pricePerSlot: 100,
    thumbnail: "https://www.coalesse.com/wp-content/uploads/2019/05/rsz_1rsz_1rsz_1rsz_118-0101935.jpg",
    extraImages: [
      "https://example.com/images/conference-room-11-1.jpg",
      "https://example.com/images/conference-room-11-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "12",
    name: "Conference Room 12",
    roomNo: 112,
    floorNo: 3,
    capacity: 26,
    pricePerSlot: 125,
    thumbnail: "https://s35891.pcdn.co/mallofasia/wp-content/uploads/sites/10/Meeting-Room.jpg.optimal.jpg",
    extraImages: [
      "https://example.com/images/conference-room-12-1.jpg",
      "https://example.com/images/conference-room-12-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "13",
    name: "Conference Room 13",
    roomNo: 113,
    floorNo: 4,
    capacity: 29,
    pricePerSlot: 160,
    thumbnail: "https://images.unsplash.com/photo-1503423571797-2d2bb372094a?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fG1lZXRpbmclMjByb29tfGVufDB8fDB8fHww",
    extraImages: [
      "https://example.com/images/conference-room-13-1.jpg",
      "https://example.com/images/conference-room-13-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "14",
    name: "Conference Room 14",
    roomNo: 114,
    floorNo: 4,
    capacity: 14,
    pricePerSlot: 70,
    thumbnail: "https://daleoffice.co.uk/wp-content/uploads/2016/09/iStock_69284827_SMALL.jpg",
    extraImages: [
      "https://example.com/images/conference-room-14-1.jpg",
      "https://example.com/images/conference-room-14-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "15",
    name: "Conference Room 15",
    roomNo: 115,
    floorNo: 4,
    capacity: 20,
    pricePerSlot: 85,
    thumbnail: "https://png.pngtree.com/thumb_back/fw800/background/20230722/pngtree-luxurious-and-modern-meeting-room-interior-design-with-3d-rendering-image_3772892.jpg",
    extraImages: [
      "https://example.com/images/conference-room-15-1.jpg",
      "https://example.com/images/conference-room-15-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "16",
    name: "Conference Room 16",
    roomNo: 116,
    floorNo: 4,
    capacity: 27,
    pricePerSlot: 135,
    thumbnail: "https://www.frontsigns.com/wp-content/uploads/2022/01/meeting-space-custom-design-solutions.jpg",
    extraImages: [
      "https://example.com/images/conference-room-16-1.jpg",
      "https://example.com/images/conference-room-16-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "17",
    name: "Conference Room 17",
    roomNo: 117,
    floorNo: 5,
    capacity: 31,
    pricePerSlot: 175,
    thumbnail: "https://www.formulainteriors.com.au/wp-content/uploads/2021/12/Meeting-Room-Fitout-2.jpg",
    extraImages: [
      "https://example.com/images/conference-room-17-1.jpg",
      "https://example.com/images/conference-room-17-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "18",
    name: "Conference Room 18",
    roomNo: 118,
    floorNo: 5,
    capacity: 12,
    pricePerSlot: 60,
    thumbnail: "https://cowello.com/wp-content/uploads/2022/07/TheLindseyBuilding.jpeg",
    extraImages: [
      "https://example.com/images/conference-room-18-1.jpg",
      "https://example.com/images/conference-room-18-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "19",
    name: "Conference Room 19",
    roomNo: 119,
    floorNo: 5,
    capacity: 23,
    pricePerSlot: 115,
    thumbnail: "https://cms.workplaceone.com/cr_images/meeting-rooms/_800x560_crop_center-center_none/sm-003_Mtg-Rm_WP1_26_Wellington_Street_E.jpg",
    extraImages: [
      "https://example.com/images/conference-room-19-1.jpg",
      "https://example.com/images/conference-room-19-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
  {
    _id: "20",
    name: "Conference Room 20",
    roomNo: 120,
    floorNo: 5,
    capacity: 30,
    pricePerSlot: 170,
    thumbnail: "https://media.licdn.com/dms/image/v2/C5612AQHRjdBvJxq61Q/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1558006914176?e=2147483647&v=beta&t=1WIVbuBTfeY1AgRaBvz3sO_VpxWiZ7Dmp85AMfMQfgI",
    extraImages: [
      "https://example.com/images/conference-room-20-1.jpg",
      "https://example.com/images/conference-room-20-2.jpg",
    ],
    amenities: [],
    isDeleted: false,
    __v: 0,
  },
];
